# fly.toml app configuration file generated for memorize-bible-verses-api-server on 2025-08-25T22:49:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memorize-bible-verses-api-server'
primary_region = 'ord'

[build]

[env]
  HOSTNAME = '0.0.0.0'
  PINO_LOG_LEVEL = 'info'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
