# fly.toml app configuration file generated for memorize-scripture-api-server on 2025-06-17T15:19:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memorize-scripture-api-server'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PINO_LOG_LEVEL = 'info'
  HOSTNAME = '0.0.0.0'
  PORT = 3000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
